/* CREATE DATABASE AND SCHEMA*/
USE DATABASE LA_DB;
USE SCHEMA LA_SCHEMA;

/* Use acccountadmin role and WH */

USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

-- Disbale the cache

ALTER SESSION SET  USE_CACHED_RESULT = FALSE;


-- Check for original table


SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

-- Use SYSTEM | BLOCK Method

--CREATE OR REPLACE TABLE SAMPLE_DATA_EX
--AS
SELECT COUNT(*) FROM  SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER TABLESAMPLE(1);



-- Use BERNOULLI | ROW Method (It is also default method 

SELECT COUNT(*) FROM  SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER TABLESAMPLE BERNOULLI (20.3) SEED(10);

-- Fixed Size Row Sampling

SELECT COUNT(*) FROM  SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER SAMPLE(100 ROWS);