/* Use Database and Schema*/
USE DATABASE LA_DB;
USE SCHEMA LA_SCHEMA;
USE WAREHOUSE WAREHOUSE_SMARTOSC;
SELECT * FROM CUSTOMER;

DROP VIEW IF EXISTS CUSTOMER_VIEW;
DROP VIEW IF EXISTS CUSTOMER_LOCATION_VIEW;

CREATE OR REPLACE VIEW CUSTOMER_VIEW AS
SELECT CUSTOMER_ID, FIRST_NAME
FROM CUSTOMER;

SELECT * from CUSTOMER_VIEW;


CREATE OR REPLACE VIEW CUSTOMER_LOCATION_VIEW AS
SELECT CUSTOMER_ID, CONCAT(ADDRESS, ', ', CITY, ', ', STATE, ', ', COUNTRY) AS LOCATION
FROM CUSTOMER;

SELECT * from CUSTOMER_LOCATION_VIEW;


-- Create a materialized view called CUSTOMER_LOCATION_MV
CREATE OR REPLACE MATERIALIZED VIEW CUSTOMER_LOCATION_MV
AS
SELECT CUSTOMER_ID, CONCAT(ADDRESS, ', ', CITY, ', ', STATE, ', ', COUNTRY) AS LOCATION
FROM CUSTOMER
WHERE STATE = 'CA';

select * from CUSTOMER_LOCATION_MV;

UPDATE CUSTOMER SET ADDRESS = '12345 Main St new car1' WHERE CUSTOMER_ID = 1;

-- Create a secure materialized view called CUSTOMER_LOCATION_MV

CREATE OR REPLACE SECURE MATERIALIZED LA_DB.LA_SCHEMA.CUSTOMER_LOCATION_VIEW CUSTOMER_LOCATION_MV_S
AS
SELECT CUSTOMER_ID, CONCAT(ADDRESS, ', ', CITY, ', ', STATE, ', ', COUNTRY) AS LOCATION
FROM CUSTOMER
WHERE STATE = 'CA';

-- Display all the views

SHOW VIEWS;

SELECT * from CUSTOMER_LOCATION_MV_S;


USE ROLE ACCOUNTADMIN;

--Grant relevant access on DB

GRANT USAGE on DATABASE LA_DB to USERADMIN;
-- Grant usage access on a schema
GRANT USAGE on SCHEMA LA_SCHEMA to USERADMIN;

-- Grant select access on views

GRANT SELECT on VIEW CUSTOMER_LOCATION_MV TO USERADMIN;
GRANT SELECT on VIEW CUSTOMER_LOCATION_MV_S TO USERADMIN;

-- Grant warehouse usage to the role

GRANT USAGE ON WAREHOUSE WAREHOUSE_SMARTOSC TO ROLE USERADMIN;


-- change the role

USE ROLE USERADMIN;
USE ROLE PUBLIC;
USE ROLE ACCOUNTADMIN;


--check DDL code

select get_ddl('view','CUSTOMER_LOCATION_MV_S');

select get_ddl('view','CUSTOMER_LOCATION_MV');

-- Run Select Queries

SELECT * from CUSTOMER_LOCATION_MV;
SELECT * from CUSTOMER_LOCATION_MV_S;










