/* CREATE DATABASE AND SCHEMA*/
USE DATABASE LA_DB;
USE SCHEMA LA_SCHEMA;

-- CREATE A PERMANENT TABLE
CREATE TABLE PERMANENT_TABLE (
  ID NUMBER,
  NAME VARCHAR,
  DATE DATE
);

-- CREATE A TRANSIENT TABLE
CREATE TRANSIENT TABLE TRANSIENT_TABLE (
  ID NUMBER,
  NAME VARCHAR,
  DATE DATE
);

-- CREATE A TEMPORARY TABLE and also use abbreviation TEMP intead of TEMPORARY
-- Also Creating Temporary table doesnt require  does not require the CREATE TABLE privilege on the schema in which the object is created.
CREATE TEMPORARY TABLE TEMPORARY_TABLE (
  ID NUMBER,
  NAME VARCHAR,
  DATE DATE
);

-- ADD DATA TO THE TABLES
INSERT INTO PERMANENT_TABLE VALUES (1, 'John', '2022-01-01');
INSERT INTO TRANSIENT_TABLE VALUES (2, 'Jane', '2022-01-02');
INSERT INTO TEMPORARY_TABLE VALUES (4, 'Jill', '2022-01-04');

-- Display TABLES METADATA

SHOW TABLES;

-- VIEW THE DATA IN THE TABLES
SELECT * FROM PERMANENT_TABLE;
SELECT * FROM TRANSIENT_TABLE;
SELECT * FROM TEMPORARY_TABLE;

-- CREATE CLONE FROM TABLES

CREATE TEMPORARY TABLE TEMPORARY_TABLE2 CLONE PERMANENT_TABLE;

SELECT * FROM TEMPORARY_TABLE2;

CREATE TRANSIENT TABLE TRANSIENT_TABLE2 CLONE PERMANENT_TABLE;

SELECT * FROM TRANSIENT_TABLE2;

CREATE TEMPORARY TABLE TEMPORARY_TABLE3 CLONE TRANSIENT_TABLE;

-- ALTER RETENTION TIME

ALTER TABLE PERMANENT_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 31;
ALTER TABLE TEMPORARY_TABLE2 SET DATA_RETENTION_TIME_IN_DAYS = 32;
ALTER TABLE TRANSIENT_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 0;

-- Display TABLES METADATA

SHOW TABLES;