/* CREATE DATABASE AND SCHEMA*/
USE DATABASE LA_DB;
USE SCHEMA LA_SCHEMA;

/* Use acccountadmin role and WH */

USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

-- Query Result Cache

--ALTER SESSION SET  USE_CACHED_RESULT = TRUE/FALSE;

SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.WEB_RETURNS limit 1000;

SELECT CURRENT_TIMESTAMP(),* FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.INVENTORY limit 10000;

SELECT CURRENT_DATE(),* FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.WEB_RETURNS limit 10000;

-- Metdata Cache Check

ALTER WAREHOUSE COMPUTE_WH SUSPEND ;

SELECT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CATALOG_SALES;


SELECT DISTINCT COUNT(*) FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.CUSTOMER_ADDRESS;

-- Warehouse Cache, for adhoc usage of warehouse recommended auto suspend is 5 minutes
-- FOr warehouse meant only for read queries, auto suspend recommended time is 10 minutes
-- Warehouse cache, Local disk cache check

ALTER SESSION SET  USE_CACHED_RESULT = FALSE;

ALTER WAREHOUSE COMPUTE_WH SUSPEND ;

ALTER WAREHOUSE COMPUTE_WH RESUME;

-- Check data in sample table

SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.INVENTORY limit 1000;




