/* CREATE DATABASE AND SCHEMA*/
USE DATABASE LA_DB;
USE SCHEMA LA_SCHEMA;

/* Use acccountadmin role and WH */

USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

-- Disbale the cache

ALTER SESSION SET  USE_CACHED_RESULT = FALSE;

--Copy from a SF table

CREATE OR REPLACE TABLE CLUSTER_SAMPLE
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCDS_SF100TCL.STORE_SALES limit 20000000;

-- Check clustering flag

SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CLUSTER_SAMPLE';


 
-- Try fining a good clustering Key

SELECT SYSTEM$CLUSTERING_INFORMATION ('CLUSTER_SAMPLE','(SS_TICKET_NUMBER)');

SELECT SYSTEM$CLUSTERING_INFORMATION ('CLUSTER_SAMPLE','(SS_SOLD_DATE_SK)');

-- Run and check the performance before Clustering

SELECT * FROM CLUSTER_SAMPLE WHERE SS_SOLD_DATE_SK = '2451226';



-- Enable Clustering

ALTER TABLE CLUSTER_SAMPLE CLUSTER BY (SS_SOLD_DATE_SK);

-- Post clustering Performance of same Query

SELECT * FROM CLUSTER_SAMPLE WHERE SS_SOLD_DATE_SK = '2451226';


-- To check clustering Depth

SELECT SYSTEM$CLUSTERING_DEPTH('CLUSTER_SAMPLE');


-- Extra commands for SUSPEND and RESUME

ALTER TABLE CLUSTER_SAMPLE SUSPEND RECLUSTER;

-- Check STATUS

SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'CLUSTER_SAMPLE';

ALTER TABLE CLUSTER_SAMPLE RESUME RECLUSTER;

-- DROP CLUSTER

ALTER TABLE CLUSTER_SAMPLE DROP CLUSTERING KEY;

